alias agi='sudo apt-get install'
alias agr='sudo apt-get remove'
alias agu='sudo apt-get update'
alias ls='ls -alh'
alias mv='mv -iv'
alias shut='sudo shutdown -h'
alias cddesk='cd ~/Desktop'
alias cddoc='cd ~/Documents'
alias cddown='cd ~/Downloads'
alias bc='bc -l'
alias untar='tar xvfz'
alias rm='rm -i'
#typos
alias ipconfig='ifconfig'
alias cd..='cd ..'
alias gs='git status'

